# Generated by Django 5.2 on 2025-05-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Cimage',
            field=models.ImageField(default='', upload_to='category_images'),
        ),
    ]
