# Generated by Django 5.2 on 2025-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='measures',
            field=models.CharField(default='', max_length=50),
        ),
    ]
