# Generated by Django 5.2 on 2025-06-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0011_alter_profile_phone_alter_profile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=' ', upload_to='profile_image'),
        ),
    ]
